holographxyz/holograph

- packages/sdk/package.json
- packages/sdk/scripts/example.ts
- packages/sdk/src/services/holograph-protocol.service.ts
- packages/sdk/src/tests/contracts/Holograph.test.ts
- packages/sdk/src/tests/example.test.ts
- packages/sdk/src/utils/transformers.ts
- pnpm-lock.yaml
- Setup Vitest (testing framework)
- Add example test
- Add some `Holograph` contract class tests
- Configure scripts
How to run the tests:
Make sure you have the following environment variables set in `packages/sdk/.env` file:
ETHEREUM_TESTNET_RPC=
ETHEREUM_MAINNET_RPC=
POLYGON_TESTNET_RPC=
POLYGON_MAINNET_RPC=
Then, run the command:
`cd packages/sdk && pnpm test`
> feat: Vitest setup

- packages/sdk/src/constants/addresses.ts
- packages/sdk/src/contracts/holograph.contract.ts
- packages/sdk/src/contracts/index.ts
- packages/sdk/src/contracts/interfaces.contract.ts
- packages/sdk/src/contracts/registry.contract.ts
- packages/sdk/src/contracts/treasury.contract.ts
- packages/sdk/src/errors/general/invalid-holograph-environment.error.ts
- packages/sdk/src/errors/holograph-error.ts
- packages/sdk/src/tests/contracts/interfaces.test.ts
- packages/sdk/src/tests/contracts/treasury.test.ts
- packages/sdk/src/utils/abitype/ethers.ts
- packages/sdk/src/utils/abitype/index.ts
- packages/sdk/src/utils/abitype/types.ts
Changes made to the package: **skd**.
- Add  `HolographInterfaces` contract read functions 
- Add  `HolographInterfaces` tests
- Change the typing for ethers contract using abitype
> Feature/HOLO 1354 add Interfaces module read functions

- packages/sdk/src/contracts/holograph.contract.ts
- packages/sdk/src/contracts/interfaces.contract.ts
- packages/sdk/src/contracts/registry.contract.ts
- packages/sdk/src/contracts/treasury.contract.ts
- packages/sdk/src/tests/contracts/interfaces.test.ts
- packages/sdk/src/tests/contracts/registry.test.ts
- Abstract contract calls avoiding lots of code duplication
- Standardize the order of params for each call (chainId first, then function name, then function params)
- General polishes
> refactor: Contract calls abstraction

- packages/sdk/src/contracts/holograph.contract.ts
- packages/sdk/src/contracts/index.ts
- packages/sdk/src/contracts/interfaces.contract.ts
- packages/sdk/src/contracts/operator.contract.ts
- packages/sdk/src/contracts/registry.contract.ts
- packages/sdk/src/contracts/treasury.contract.ts
- packages/sdk/src/services/holograph-protocol.service.ts
- packages/sdk/src/tests/contracts/operator.test.ts
- packages/sdk/src/utils/abitype/index.ts
- Add Operator contract class
- Add tests to this new class
- Add `AbiFunctionArgs`, and `AbiFunctionReturn` utility types
- Make `functionName` param of `_getContractFunction` helper type-safe for all contract classes
> HOLO-1200: Add Operator class

- packages/sdk/src/constants/abi/develop/LayerZeroModule.ts
- packages/sdk/src/constants/abi/experimental/LayerZeroModule.ts
- packages/sdk/src/constants/abi/mainnet/LayerZeroModule.ts
- packages/sdk/src/constants/abi/testnet/LayerZeroModule.ts
- packages/sdk/src/constants/addresses.ts
- packages/sdk/src/contracts/holograph.contract.ts
- packages/sdk/src/contracts/index.ts
- packages/sdk/src/contracts/interfaces.contract.ts
- packages/sdk/src/contracts/layer-zero-module.contract.ts
- packages/sdk/src/contracts/operator.contract.ts
- packages/sdk/src/contracts/registry.contract.ts
- packages/sdk/src/contracts/treasury.contract.ts
- packages/sdk/src/tests/contracts/layer-zero-module.test.ts
- Add LayerZeroModule contract class
- Add tests to this new class
- Update LayzerZeroModule ABIs
- Add `layerZeroModule` contract constants
- Standardize `@returns`, `bridges,  and `bridging` spelling
> HOLO-1202: Add LayerZeroModule contract class

- packages/sdk/src/contracts/factory.contract.ts
- packages/sdk/src/contracts/holograph.contract.ts
- packages/sdk/src/contracts/index.ts
- packages/sdk/src/contracts/interfaces.contract.ts
- packages/sdk/src/contracts/layer-zero-module.contract.ts
- packages/sdk/src/contracts/operator.contract.ts
- packages/sdk/src/contracts/registry.contract.ts
- packages/sdk/src/contracts/treasury.contract.ts
- packages/sdk/src/services/holograph-protocol.service.ts
- packages/sdk/src/utils/decoders.ts
- Add Factory contract class and its functions (read & write)
- Add LayerZeroModule contract write functions
- Add `@readonly` missing tags 
- Handle read/write on `_getContractFunction` helper for some contract classes
- General polishes
> HOLO-1372, HOLO-1374: Add Factory + LayerZeroModule write functions

- packages/sdk/src/contracts/registry.contract.ts
- packages/sdk/src/tests/contracts/registry.test.ts
- packages/sdk/src/utils/contracts.ts
- add write functions to `Registry` contract class.
- add missing read functions to `Registry` contract class.
> Improvement / HOLO 1369 Holograph Registry Write Functions

- packages/sdk/src/constants/abi/develop/HolographTreasury.ts
- packages/sdk/src/constants/abi/mainnet/HolographTreasury.ts
- packages/sdk/src/constants/abi/testnet/HolographTreasury.ts
- packages/sdk/src/contracts/treasury.contract.ts
- packages/sdk/src/tests/contracts/treasury.test.ts
- Add `Treasury` contract write functions.
- Add `Treasury` initial tests setup.
> Improvement / HOLO 1368 Holograph Treasury Write Functions

- packages/sdk/src/contracts/bridge.contract.ts
- packages/sdk/src/contracts/factory.contract.ts
- packages/sdk/src/contracts/holograph.contract.ts
- packages/sdk/src/contracts/index.ts
- packages/sdk/src/contracts/interfaces.contract.ts
- packages/sdk/src/contracts/layer-zero-module.contract.ts
- packages/sdk/src/contracts/operator.contract.ts
- packages/sdk/src/contracts/ovm-gas-price-oracle.contract.ts
- packages/sdk/src/contracts/registry.contract.ts
- packages/sdk/src/contracts/treasury.contract.ts
- packages/sdk/src/services/holograph-protocol.service.ts
- packages/sdk/src/tests/contracts/bridge.test.ts
- packages/sdk/src/tests/contracts/factory.test.ts
- packages/sdk/src/tests/contracts/holograph.test.ts
- packages/sdk/src/tests/contracts/interfaces.test.ts
- packages/sdk/src/tests/contracts/operator.test.ts
- packages/sdk/src/tests/contracts/ovm-gas-price-oracle.test.ts
- packages/sdk/src/tests/contracts/registry.test.ts
- packages/sdk/src/tests/contracts/treasury.test.ts
- packages/sdk/src/utils/contracts.ts
- Add Bridge contract class read and write functions
- Setup initial tests for the `bridge.contract.ts` file
- Improve documentation
- Fix typos
> HOLO-1373: Add Bridge contract class

- packages/sdk/src/assets/nft.ts
- packages/sdk/src/assets/nft.validation.ts
- packages/sdk/src/errors/assets/not-minted-nft.error.ts
- packages/sdk/src/errors/assets/update-minted-nft.error.ts
- packages/sdk/src/errors/holograph-error.ts
- packages/sdk/src/tests/assets/nft.test.ts
- packages/sdk/src/utils/decorators.ts
- packages/sdk/src/utils/helpers.ts
- Add NFT asset class
- Add validation
- Add error mapping/handling
- Add `IsNotMinted()` decorator
- Add tests
> HOLO-1394: Add NFT asset class

- packages/networks/package.json
> Bump networks version to 0.2.2

- packages/sdk/src/constants/gas-controllers/legacy-collection-deploy.ts
- packages/sdk/src/constants/gas-controllers/moe-collection-deploy.ts
- packages/sdk/src/contracts/factory.contract.ts
- packages/sdk/src/contracts/holograph-base.contract.ts
- packages/sdk/src/tests/contracts/operator.test.ts
- packages/sdk/src/tests/setup.ts
- packages/sdk/src/utils/types.ts
- Enable gas estimation for contract function calls
- Support override options object to be passed to the contract write calls (https://viem.sh/docs/contract/writeContract#gasprice-optional)
- Make options type-safe
> improvement: Support gas estimation for contract functions + overrides object

- packages/sdk/scripts/get-logs.ts
- packages/sdk/src/assets/README.md
- packages/sdk/src/assets/collection-legacy.ts
- packages/sdk/src/assets/collection-moe.ts
- packages/sdk/src/assets/collection.validation.ts
- packages/sdk/src/constants/addresses.ts
- packages/sdk/src/contracts/factory.contract.ts
- packages/sdk/src/tests/assets/collection-legacy.test.ts
- packages/sdk/src/tests/assets/collection-moe.test.ts
- packages/sdk/src/tests/setup.ts
- packages/sdk/src/utils/helpers.ts
- packages/sdk/src/utils/types.ts
- packages/sdk/vitest.config.js
- Create `_estimateGasForDeployingCollection` method for `HolographCollectionLegacy` class
- Add tests to `collection-legacy.ts` file
- Create `_estimateGasForDeployingCollection` method for `HolographMoeERC721DropV1` and `V2` classes
- Add tests to `collection-moe.ts` file
- Add docs
- General improvements
> HOLO-1418: Estimate gas for collection deploys, and add more tests to collection classes

- packages/networks/package.json
- packages/networks/src/networks.ts
- Add starter info for Linea Sepolia
- LZ isn't deployed there yet
- Bump version number
> Add initial object for Linea Sepolia

- packages/networks/package.json
- packages/networks/src/networks.ts
- packages/networks/src/utils.ts
- Revert some changes to avoid networks package type issues on the CLI
> fix: Fix network type issues

- packages/networks/package.json
One more bump with the build of networks package
> Bump version to 0.2.7

- packages/sdk/src/assets/collection-legacy.ts
- packages/sdk/src/assets/collection-moe.ts
- packages/sdk/src/contracts/factory.contract.ts
- packages/sdk/src/contracts/holograph-base.contract.ts
- packages/sdk/src/utils/types.ts
- Remove gas estimation wrapper from each contract individually
> refactor: Remove gas wrapper extra functions

- packages/sdk/src/tests/assets/nft-moe.test.ts
- Add tests back to the MOE NFT asset class (removing their `skip`)
> chore: Add MOE NFT tests back

- packages/sdk/src/assets/README.md
- packages/sdk/src/assets/collection-legacy.ts
- packages/sdk/src/assets/collection-moe.ts
- packages/sdk/src/assets/collection.validation.ts
- packages/sdk/src/assets/nft-moe.ts
- packages/sdk/src/assets/nft.ts
- packages/sdk/src/constants/gas-controllers/index.ts
- packages/sdk/src/constants/gas-controllers/legacy-collection-deploy.ts
- packages/sdk/src/constants/gas-controllers/moe-nft-mint.ts
- packages/sdk/src/constants/gas-controllers/nft-mint.ts
- packages/sdk/src/contracts/bridge.contract.ts
- packages/sdk/src/contracts/factory.contract.ts
- packages/sdk/src/contracts/holograph-base.contract.ts
- packages/sdk/src/contracts/operator.contract.ts
- packages/sdk/src/tests/assets/collection-legacy.test.ts
- packages/sdk/src/tests/assets/collection-moe.test.ts
- packages/sdk/src/tests/assets/nft-moe.test.ts
- packages/sdk/src/tests/assets/nft.test.ts
- packages/sdk/src/tests/utils/encoders.test.ts
- packages/sdk/src/utils/decoders.ts
- packages/sdk/src/utils/encoders.ts
- packages/sdk/src/utils/helpers.ts
- packages/sdk/src/utils/types.ts
- Improved types throughout the codebase.
- Enhanced function reutilization to promote code reuse and maintainability.
- Modified class modifiers for improved encapsulation and access control.
- Updated test files to accommodate the execution of non-public functions.
> Refactor/ Improved types, function reutilization, and class modifiers

- packages/networks/package.json
- packages/networks/src/networks.ts
Add safe address for Zora and bump version
> Add safe address for Zora

- packages/sdk/src/assets/bridge-asset.ts
- packages/sdk/src/assets/bridge-collection.ts
- packages/sdk/src/assets/collection-legacy.ts
- packages/sdk/src/constants/gas-controllers/bridge-nft.ts
- packages/sdk/src/constants/gas-controllers/index.ts
- packages/sdk/src/contracts/holograph-base.contract.ts
- packages/sdk/src/contracts/operator.contract.ts
- packages/sdk/src/tests/assets/bridge-asset.test.ts
- packages/sdk/src/tests/assets/bridge-collection.test.ts
- packages/sdk/src/tests/assets/collection-legacy.test.ts
- packages/sdk/src/utils/gas.ts
- packages/sdk/src/utils/types.ts
- Add `simulateContract` functions to `HolographBaseContract`, this functions should be use for `staticCall`.
- Introduce a base class, `BridgeAsset`, to serve as the foundation for all specific bridge classes. 
- Create `BridgeCollection` class
- Create `utils/gas` containing functions to estimate gas costs. This initial implementation copies functionality from the frontend code. It needs further improvements.
- Create gas controller for bridge collections
- Add minor improvements
> Feature / HOLO 1396 Add BridgeCollection Class to SDK

- packages/networks/package.json
- packages/networks/src/networks.ts
- packages/networks/src/test-network-key.ts
- Add a function to generate `NETWORK_KEY_BY_RPC_URL` dynamically
- Add the multisig address for Linea Goerli
> Make the NETWORK_KEY_BY_RPC_URL object dynamic

- packages/sdk/src/assets/bridge-collection.ts
- packages/sdk/src/assets/bridge-nft.ts
- packages/sdk/src/assets/collection-legacy.ts
- packages/sdk/src/assets/collection-moe.ts
- packages/sdk/src/assets/collection.validation.ts
- packages/sdk/src/assets/nft-moe.ts
- packages/sdk/src/assets/nft.ts
- packages/sdk/src/assets/nft.validation.ts
- packages/sdk/src/errors/assets/not-minted-nft.error.ts
- packages/sdk/src/errors/assets/update-deployed-collection.error.ts
- packages/sdk/src/errors/assets/update-minted-nft.error.ts
- packages/sdk/src/errors/holograph-error.ts
- packages/sdk/src/tests/assets/bridge-asset.test.ts
- packages/sdk/src/tests/assets/bridge-collection.test.ts
- packages/sdk/src/tests/assets/bridge-nft.test.ts
- packages/sdk/src/tests/assets/nft-moe.test.ts
- packages/sdk/src/tests/assets/nft.test.ts
- packages/sdk/src/tests/utils/decoders.test.ts
- packages/sdk/src/tests/utils/encoders.test.ts
- packages/sdk/src/utils/decoders.ts
- packages/sdk/src/utils/decorators.ts
- packages/sdk/src/utils/encoders.ts
- packages/sdk/src/utils/types.ts
- Make `NFT` and `ERC` prefix uppercase
- Order public and private functions in the asset class files
- Standardize assets setters
- Add `IsNotDeployed()` decorator
> refactor: General adjustments

- packages/sdk/src/assets/bridge-asset.ts
- packages/sdk/src/assets/bridge-collection.ts
- packages/sdk/src/assets/bridge-nft.ts
- packages/sdk/src/utils/types.ts
> Refactor / Add GasSettings type

- packages/networks/src/index.ts
- packages/networks/src/utils.ts
- Add `supportedNetworkChainIds`
> Improvement / add supportedNetworkChainIds to networks package

- packages/sdk/package.json
- packages/sdk/src/index.ts
- packages/sdk/tsconfig.json
- Add `sdk` package exports to make it easier to import from root dir like: 
`import { HolographConfig } from '@holographxyz/sdk'`
> chore: Add exports

- packages/sdk/LICENSE.md
- Add license to the SDK package
> chore: Add license to SDK package

- packages/sdk/package.json
- packages/sdk/tsconfig.json
Changes made to the package: **PACKAGE_NAME**.
- bump version
> bump version 0.1.0-alpha.1

- packages/sdk/package.json
- packages/sdk/tsconfig.json
- Adjust SDK package root file
- Update tsconfig.json
> fix: Adjust SDK package root file

- packages/sdk/package.json
- packages/sdk/src/index.ts
- packages/sdk/src/services/wallet.service.ts
- Remove `pino` logger imports as an attempt to fix the package installation on FE
> chore: Hide pino logger imports

- packages/sdk/package.json
- packages/sdk/src/services/logger.service.ts
- pnpm-lock.yaml
- Remove `pino-pretty`
- Add `browser` object config inside `pino` config
> chore: Pino logger updates

- packages/sdk/package.json
- packages/sdk/src/index.ts
- packages/sdk/src/services/logger.service.ts
- packages/sdk/src/services/wallet.service.ts
- pnpm-lock.yaml
- Update logger service to use global console.log instead of pino for FE compatibility at this moment
> refactor: Update logger service

- packages/sdk/package.json
- packages/sdk/src/services/logger.service.ts
- packages/sdk/src/utils/types.ts
- pnpm-lock.yaml
- Remove `pino` and `pino-pretty` packages in the SDK for FE compatibility
> chore: Remove pino

- packages/sdk/package.json
- packages/sdk/tsup.config.ts
- pnpm-lock.yaml
- Add `tsup` to cover the SDK package build process
> feat: Add tsup to the SDK build process

- packages/sdk/package.json
- packages/sdk/src/assets/bridge-asset.ts
- packages/sdk/src/assets/bridge-collection.ts
- packages/sdk/src/assets/bridge-nft.ts
- packages/sdk/src/services/logger.service.ts
- packages/sdk/tsup.config.ts
- Fix SDK package build process
- Make the SDK installable on FE codebases
- Get the build faster
- Reduce the package size by almost 90% ⚡
- Refactor the logger service
- Fix the bug where SDK package sub-dependencies were not being installed
> fix: Fix SDK package build

- packages/environment/package.json
- pnpm-lock.yaml
Changes made to the package: **holograph environment**.
- add setEnvironment
- bump version
> chore/add setEnvironment function and bump version

- packages/sdk/package.json
- packages/sdk/src/assets/collection-moe.ts
- packages/sdk/src/assets/collection.validation.ts
- packages/sdk/src/assets/nft.validation.ts
- packages/sdk/src/services/config.service.ts
- packages/sdk/src/services/wallet.service.ts
- packages/sdk/src/utils/types.ts
- pnpm-lock.yaml
- Extend HolographWallet config to work on the FE with a provider
> feat: Extend HolographWallet config

- packages/sdk/package.json
- packages/sdk/scripts/example.ts
- packages/sdk/src/assets/collection-legacy.ts
- packages/sdk/src/assets/collection-moe.ts
- packages/sdk/src/assets/nft-moe.ts
- packages/sdk/src/assets/nft.ts
- packages/sdk/src/constants/addresses.ts
- packages/sdk/src/errors/general/missing-network-information.error.ts
- packages/sdk/src/services/config.service.ts
- packages/sdk/src/services/providers.service.ts
- packages/sdk/src/services/wallet.service.ts
- packages/sdk/src/tests/assets/bridge-asset.test.ts
- packages/sdk/src/tests/assets/bridge-collection.test.ts
- packages/sdk/src/tests/assets/bridge-nft.test.ts
- packages/sdk/src/tests/assets/collection-legacy.test.ts
- packages/sdk/src/tests/assets/collection-moe.test.ts
- packages/sdk/src/tests/assets/nft-moe.test.ts
- packages/sdk/src/tests/assets/nft.test.ts
- packages/sdk/src/utils/types.ts
- Add client provider support on Config class
- Add client provider support on Providers class
- Remove code duplication on HolographWallet class (`networks` and `chainsRpc`). Set the standard key as `networks`, and the standard value as per `networks` from Holograph config class
> refactor: Add client provider logic to the Holograph config class

- packages/sdk/package.json
- packages/sdk/src/assets/collection-legacy.ts
- packages/sdk/src/assets/collection-moe.ts
- Fix chain type logic on the collection deployment feature
> fix: Fix collection deployment chain type

- packages/sdk/package.json
- packages/sdk/src/assets/bridge-collection.ts
- packages/sdk/src/assets/collection-legacy.ts
- packages/sdk/src/assets/collection-moe.ts
- packages/sdk/src/errors/general/viem.error.ts
- Format tx/signature rejected error message
> chore: Format tx/signature rejected error message

- packages/sdk/package.json
- packages/sdk/src/assets/collection-moe.ts
- packages/sdk/src/constants/gas-controllers/bridge-nft.ts
- packages/sdk/src/constants/gas-controllers/index.ts
- packages/sdk/src/constants/gas-controllers/legacy-collection-deploy.ts
- packages/sdk/src/constants/gas-controllers/moe-collection-deploy.ts
- packages/sdk/src/constants/gas-controllers/moe-nft-mint.ts
- packages/sdk/src/constants/gas-controllers/nft-mint.ts
- packages/sdk/src/tests/assets/collection-moe.test.ts
- packages/sdk/src/utils/encoders.ts
- packages/sdk/src/utils/helpers.ts
- packages/sdk/src/utils/types.ts
- pnpm-lock.yaml
- Update the MOE collection deployment flow to reflect the exact FE implementation
- Update gas controllers
> refactor: Update MOE collection deployment flow

- packages/sdk/src/assets/bridge-asset.ts
- packages/sdk/src/assets/bridge-collection.ts
- packages/sdk/src/assets/bridge-nft.ts
- packages/sdk/src/assets/collection-moe.ts
- packages/sdk/src/contracts/registry.contract.ts
- packages/sdk/src/contracts/treasury.contract.ts
- packages/sdk/src/utils/types.ts
- reduce constructor params for bridge collection and bridge NFT classes
- code clean up
> Improvement / reduce constructor params

- packages/sdk/package.json
- packages/sdk/src/assets/bridge-asset.ts
- packages/sdk/src/assets/collection-legacy.ts
- packages/sdk/src/assets/collection-moe.ts
- packages/sdk/src/tests/assets/bridge-asset.test.ts
- Adjust Bridge NFT flow (we were accidentally using the factory address instead of the collection contract address).
> fix: Bridge NFT adjustments

- packages/sdk/package.json
- packages/sdk/src/index.ts
- packages/sdk/src/services/providers.service.ts
- packages/sdk/src/utils/decoders.ts
- packages/sdk/src/utils/types.ts
- Add `getTransaction` and `getTransactionReceipt` to the providers service
- Add `OperatorJob` type
- adjust exports
> Chore / add transactions functions to providers service and adjust exports

- packages/sdk/src/assets/bridge-erc20.ts
- packages/sdk/src/index.ts
- packages/sdk/src/tests/assets/bridge-erc20.test.ts
- packages/sdk/src/tests/setup.ts
- packages/sdk/src/utils/types.ts
- Add `BridgeERC20` class
- Add bridge ERC20 tests
> Feature / HOLO 1397 Add Bridge ERC20Token Class to SDK

- packages/sdk/package.json
- packages/sdk/src/assets/nft.ts
- packages/sdk/src/assets/open-edition-nft.ts
- packages/sdk/src/constants/abi/develop/HolographOperator.ts
- packages/sdk/src/constants/abi/experimental/HolographOperator.ts
- packages/sdk/src/constants/abi/mainnet/HolographOperator.ts
- packages/sdk/src/constants/abi/testnet/HolographOperator.ts
- packages/sdk/src/contracts/bridge.contract.ts
- packages/sdk/src/contracts/cxip-erc721.contract.ts
- packages/sdk/src/contracts/factory.contract.ts
- packages/sdk/src/contracts/holograph-base.contract.ts
- packages/sdk/src/contracts/holograph.contract.ts
- packages/sdk/src/contracts/interfaces.contract.ts
- packages/sdk/src/contracts/layer-zero-module.contract.ts
- packages/sdk/src/contracts/open-edition-erc721.contract.ts
- packages/sdk/src/contracts/operator.contract.ts
- packages/sdk/src/contracts/ovm-gas-price-oracle.contract.ts
- packages/sdk/src/contracts/registry.contract.ts
- packages/sdk/src/contracts/treasury.contract.ts
- packages/sdk/src/index.ts
- packages/sdk/src/services/holograph-protocol.service.ts
- packages/sdk/src/tests/contracts/bridge.test.ts
- packages/sdk/src/tests/contracts/factory.test.ts
- packages/sdk/src/tests/contracts/holograph-interfaces.test.ts
- packages/sdk/src/tests/contracts/holograph.test.ts
- packages/sdk/src/tests/contracts/layer-zero-module.test.ts
- packages/sdk/src/tests/contracts/operator.test.ts
- packages/sdk/src/tests/contracts/registry.test.ts
- packages/sdk/src/utils/contracts.ts
- packages/sdk/src/utils/types.ts
This PR addresses the need to ensure type safety by adjusting the return types in our contract functions.
- Updated the return types for several contract functions to align with our type definitions.
- Modified the associated tests to reflect the changes in return types.
- Add new Operator contract functions
> Improvement / HOLO 1532 Review return values for contracts
